version: '3'

services:
  # React App
  client:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run client:dev:docker
    ports:
      - 4200:4200

  # Express App
  proxy:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run proxy:dev:docker
    ports:
      - 3333:3333 # API Entry port
      - 4311:4311 # Server Debugging port

volumes:
  mono-node-modules: null
